apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"frontend","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"frontend"}}}
    creationTimestamp: "2025-12-26T05:39:33Z"
    name: frontend
    namespace: default
    resourceVersion: "64786"
    uid: 55b85cfe-41e6-497a-a2e4-ff362ded7d56
  spec:
    clusterIP: 10.108.6.58
    clusterIPs:
    - 10.108.6.58
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"gateway-service","namespace":"default"},"spec":{"ports":[{"port":9091,"targetPort":9091}],"selector":{"app":"gateway-service"}}}
    creationTimestamp: "2025-12-26T05:39:30Z"
    name: gateway-service
    namespace: default
    resourceVersion: "64673"
    uid: bcf6c9b6-0845-474b-a69d-e0200a7ae175
  spec:
    clusterIP: 10.98.7.126
    clusterIPs:
    - 10.98.7.126
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9091
      protocol: TCP
      targetPort: 9091
    selector:
      app: gateway-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-12-08T13:14:11Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "236"
    uid: dc66ca83-375f-4077-9a95-ab8cd39a0b69
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mysql","namespace":"default"},"spec":{"clusterIP":"None","ports":[{"port":3306,"targetPort":3306}],"selector":{"app":"mysql"}}}
    creationTimestamp: "2025-12-26T05:28:38Z"
    name: mysql
    namespace: default
    resourceVersion: "63071"
    uid: c37acc41-1ee6-4190-b713-bed22d5630b7
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: mysql
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"order-service","namespace":"default"},"spec":{"ports":[{"port":8083,"targetPort":8083}],"selector":{"app":"order-service"}}}
    creationTimestamp: "2025-12-26T05:39:31Z"
    name: order-service
    namespace: default
    resourceVersion: "64740"
    uid: a6e41fac-da9b-4453-b392-1b08cbd704c1
  spec:
    clusterIP: 10.107.68.172
    clusterIPs:
    - 10.107.68.172
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
    selector:
      app: order-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"payment-service","namespace":"default"},"spec":{"ports":[{"port":8084,"targetPort":8084}],"selector":{"app":"payment-service"}}}
    creationTimestamp: "2025-12-26T05:39:32Z"
    name: payment-service
    namespace: default
    resourceVersion: "64767"
    uid: 44887d3f-faea-4158-b33d-10dd49d1bd0a
  spec:
    clusterIP: 10.98.251.131
    clusterIPs:
    - 10.98.251.131
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
    selector:
      app: payment-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"product-service","namespace":"default"},"spec":{"ports":[{"port":8082,"targetPort":8082}],"selector":{"app":"product-service"}}}
    creationTimestamp: "2025-12-26T05:39:31Z"
    name: product-service
    namespace: default
    resourceVersion: "64723"
    uid: 3e7728d7-912b-46a7-abef-0c186b7b27aa
  spec:
    clusterIP: 10.103.122.122
    clusterIPs:
    - 10.103.122.122
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: product-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"user-service","namespace":"default"},"spec":{"ports":[{"port":8081,"targetPort":8081}],"selector":{"app":"user-service"}}}
    creationTimestamp: "2025-12-26T05:39:30Z"
    name: user-service
    namespace: default
    resourceVersion: "64700"
    uid: 656fd595-a2e8-4f8d-9dc6-a6069c922128
  spec:
    clusterIP: 10.105.178.72
    clusterIPs:
    - 10.105.178.72
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: user-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
