apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ghcr.io/amy397/product-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/product_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root1234
            - name: FILE_UPLOAD_DIR
              value: /app/uploads/products
            - name: IMAGE_BASE_URL
              value: http://shop.local/images/products
            - name: FILE_BASEURL
              value: http://shop.local/images/products
          volumeMounts:
            - name: product-images
              mountPath: /app/uploads/products
      volumes:
        - name: product-images
          persistentVolumeClaim:
            claimName: product-images-pvc
